repos:
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        args: ["--line-length", "120"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]

  - repo: https://github.com/charliermarsh/ruff
    rev: 0.0.291
    hooks:
      - id: ruff
        args: ["--line-length", "120"]


